import { IAppointmentRepository } from "../../interfaces/IAppointmentRepository";
import { Appointment } from "../../../domain/entities/Appointment";
import { BookingChannel, BookedByRole } from "../../../domain/common/enums";

interface BookAppointmentRequest {
  appointmentDate: string | Date;
  reason: string;
  doctorId: string;
  patientId: string;
  bookedById: string;
  bookedByRole: BookedByRole;
  channel: BookingChannel;
  createdByUserAccountId: string;
}

export class BookAppointmentUseCase {
  constructor(private repo: IAppointmentRepository) {}

  async execute(data: BookAppointmentRequest): Promise<Appointment> {
    const appointment = new Appointment(
      undefined, // id generated by Prisma
      new Date(data.appointmentDate),
      data.reason,
      data.channel,
      data.createdByUserAccountId,
      data.bookedById,
      data.bookedByRole,
      data.doctorId,
      data.patientId
    );

    await this.repo.create(appointment);

    return appointment;
  }
}

